# CARS DATASET (Audi, BMW, Ford, Hyundai, Skoda, VW)

**Working on Real Project with Python**

This dataset is the stacked version of 100,000 UK Used Car Data set present in Kaggle. Here I have combined the used car information of 7 brands namely Audi, BMW, Skoda, Ford, Volkswagen, Toyota and Hyundai.


This data is available as a CSV file, I am going to analyze this dataset using Pandas Dataframe.

In [27]:
import pandas as pd

In [28]:
car=pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\cars_dataset.csv")

In [29]:
car

model  year  price transmission  mileage fuelType    tax   mpg  \
0           A1  2017  12500       Manual    15735   Petrol  150.0  55.4   
1           A6  2016  16500    Automatic    36203   Diesel   20.0  64.2   
2           A1  2016  11000       Manual    29946   Petrol   30.0  55.4   
3           A4  2017  16800    Automatic    25952   Diesel  145.0  67.3   
4           A3  2019  17300       Manual     1998   Petrol  145.0  49.6   
...        ...   ...    ...          ...      ...      ...    ...   ...   
72430      I30  2016   8680       Manual    25906   Diesel    0.0  78.4   
72431      I40  2015   7830       Manual    59508   Diesel   30.0  65.7   
72432      I10  2017   6830       Manual    13810   Petrol   20.0  60.1   
72433   Tucson  2018  13994       Manual    23313   Petrol  145.0  44.8   
72434   Tucson  2016  15999    Automatic    11472   Diesel  125.0  57.6   

       engineSize     Make  
0             1.4     audi  
1             2.0     audi  
2             1.4     audi  
3             2.0     audi  
4             1.0     audi  
...           ...      ...  
72430         1.6  Hyundai  
72431         1.7  Hyundai  
72432         1.0  Hyundai  
72433         1.6  Hyundai  
72434         1.7  Hyundai  

[72435 rows x 10 columns]

In [30]:
car.head()

model  year  price transmission  mileage fuelType    tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150.0  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20.0  64.2         2.0   
2    A1  2016  11000       Manual    29946   Petrol   30.0  55.4         1.4   
3    A4  2017  16800    Automatic    25952   Diesel  145.0  67.3         2.0   
4    A3  2019  17300       Manual     1998   Petrol  145.0  49.6         1.0   

   Make  
0  audi  
1  audi  
2  audi  
3  audi  
4  audi

 **1. ( For Data Cleaning ) - Finding all Null Values in the dataset. If there is any null value in any column, then i will fill it with the mean of that column.**

In [31]:
car.shape

(72435, 10)

Here we have 72435 rows and 10 columns

In [32]:
car.isnull()

model   year  price  transmission  mileage  fuelType    tax    mpg  \
0      False  False  False         False    False     False  False  False   
1      False  False  False         False    False     False  False  False   
2      False  False  False         False    False     False  False  False   
3      False  False  False         False    False     False  False  False   
4      False  False  False         False    False     False  False  False   
...      ...    ...    ...           ...      ...       ...    ...    ...   
72430  False  False  False         False    False     False  False  False   
72431  False  False  False         False    False     False  False  False   
72432  False  False  False         False    False     False  False  False   
72433  False  False  False         False    False     False  False  False   
72434  False  False  False         False    False     False  False  False   

       engineSize   Make  
0           False  False  
1           False  False  
2           False  False  
3           False  False  
4           False  False  
...           ...    ...  
72430       False  False  
72431       False  False  
72432       False  False  
72433       False  False  
72434       False  False  

[72435 rows x 10 columns]

In [33]:
car.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             3
mpg             0
engineSize      0
Make            0
dtype: int64

In [34]:
car['tax'].fillna(car['tax'].mean())

0        150.0
1         20.0
2         30.0
3        145.0
4        145.0
         ...  
72430      0.0
72431     30.0
72432     20.0
72433    145.0
72434    125.0
Name: tax, Length: 72435, dtype: float64

In [35]:
car['tax'].fillna(car['tax'].mean(), inplace=True)

In [36]:
car.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
Make            0
dtype: int64

**( Based on Value Counts )- Now I will check what are the different types of Make are there in my dataset. And, what is the count (occurrence) of each make in the data.**

In [37]:
car.head(2)

model  year  price transmission  mileage fuelType    tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150.0  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20.0  64.2         2.0   

   Make  
0  audi  
1  audi

In [39]:
car['Make'].value_counts()

Ford       17964
vw         15157
BMW        10781
audi       10668
toyota      6738
skoda       6267
Hyundai     4860
Name: Make, dtype: int64

**( Filtering ) - Show all the records where it is a petrol car.**

In [40]:
car.head(2)

model  year  price transmission  mileage fuelType    tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150.0  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20.0  64.2         2.0   

   Make  
0  audi  
1  audi

In [41]:
car['fuelType'].isin(['Petrol'])

0         True
1        False
2         True
3        False
4         True
         ...  
72430    False
72431    False
72432     True
72433     True
72434    False
Name: fuelType, Length: 72435, dtype: bool

In [42]:
car[car['fuelType'].isin(['Petrol'])]

model  year  price transmission  mileage fuelType    tax   mpg  \
0           A1  2017  12500       Manual    15735   Petrol  150.0  55.4   
2           A1  2016  11000       Manual    29946   Petrol   30.0  55.4   
4           A3  2019  17300       Manual     1998   Petrol  145.0  49.6   
5           A1  2016  13900    Automatic    32260   Petrol   30.0  58.9   
8           A3  2015  10200       Manual    46112   Petrol   20.0  60.1   
...        ...   ...    ...          ...      ...      ...    ...   ...   
72425      I10  2018   7200       Manual    17879   Petrol  145.0  60.1   
72426      I10  2018   7995       Manual     8851   Petrol  145.0  60.1   
72427      I10  2018   7200       Manual    14788   Petrol  150.0  60.1   
72432      I10  2017   6830       Manual    13810   Petrol   20.0  60.1   
72433   Tucson  2018  13994       Manual    23313   Petrol  145.0  44.8   

       engineSize     Make  
0             1.4     audi  
2             1.4     audi  
4             1.0     audi  
5             1.4     audi  
8             1.4     audi  
...           ...      ...  
72425         1.0  Hyundai  
72426         1.0  Hyundai  
72427         1.0  Hyundai  
72432         1.0  Hyundai  
72433         1.6  Hyundai  

[40370 rows x 10 columns]

**( Filtering ) - Show all the records where it is a Diesel car.**

In [43]:
car[car['fuelType'].isin(['Diesel'])]

model  year  price transmission  mileage fuelType    tax   mpg  \
1             A6  2016  16500    Automatic    36203   Diesel   20.0  64.2   
3             A4  2017  16800    Automatic    25952   Diesel  145.0  67.3   
6             A6  2016  13250    Automatic    76788   Diesel   30.0  61.4   
7             A4  2016  11750       Manual    75185   Diesel   20.0  70.6   
11            A6  2016  16500    Automatic    52198   Diesel  125.0  57.6   
...          ...   ...    ...          ...      ...      ...    ...   ...   
72428     Tucson  2016  12495       Manual    35000   Diesel   30.0  61.7   
72429   Santa Fe  2019  29995    Semi-Auto     1567   Diesel  145.0  39.8   
72430        I30  2016   8680       Manual    25906   Diesel    0.0  78.4   
72431        I40  2015   7830       Manual    59508   Diesel   30.0  65.7   
72434     Tucson  2016  15999    Automatic    11472   Diesel  125.0  57.6   

       engineSize     Make  
1             2.0     audi  
3             2.0     audi  
6             2.0     audi  
7             2.0     audi  
11            2.0     audi  
...           ...      ...  
72428         1.7  Hyundai  
72429         2.2  Hyundai  
72430         1.6  Hyundai  
72431         1.7  Hyundai  
72434         1.7  Hyundai  

[28918 rows x 10 columns]

**( Removing unwanted records ) - Remove all the records (rows) where tax is greater than 150.**

In [44]:
car.head(2)

model  year  price transmission  mileage fuelType    tax   mpg  engineSize  \
0    A1  2017  12500       Manual    15735   Petrol  150.0  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20.0  64.2         2.0   

   Make  
0  audi  
1  audi

In [62]:
car['tax']>150

0        False
1        False
2        False
3        False
4        False
         ...  
72430    False
72431    False
72432    False
72433    False
72434    False
Name: tax, Length: 72435, dtype: bool

In [64]:
car[~(car['tax']>150)]

model  year  price transmission  mileage fuelType    tax   mpg  \
0           A1  2016  12500       Manual    15735   Petrol  150.0  55.4   
1           A6  2016  16500    Automatic    36203   Diesel   20.0  64.2   
2           A1  2016  11000       Manual    29946   Petrol   30.0  55.4   
3           A4  2016  16800    Automatic    25952   Diesel  145.0  67.3   
4           A3  2016  17300       Manual     1998   Petrol  145.0  49.6   
...        ...   ...    ...          ...      ...      ...    ...   ...   
72430      I30  2016   8680       Manual    25906   Diesel    0.0  78.4   
72431      I40  2016   7830       Manual    59508   Diesel   30.0  65.7   
72432      I10  2016   6830       Manual    13810   Petrol   20.0  60.1   
72433   Tucson  2016  13994       Manual    23313   Petrol  145.0  44.8   
72434   Tucson  2016  15999    Automatic    11472   Diesel  125.0  57.6   

       engineSize     Make  
0             1.4     audi  
1             2.0     audi  
2             1.4     audi  
3             2.0     audi  
4             1.0     audi  
...           ...      ...  
72430         1.6  Hyundai  
72431         1.7  Hyundai  
72432         1.0  Hyundai  
72433         1.6  Hyundai  
72434         1.7  Hyundai  

[66908 rows x 10 columns]

 **( Applying function on a column ) - Increase all the values of 'tax' column by 3.**

In [65]:
car.head(2)

model  year  price transmission  mileage fuelType    tax   mpg  engineSize  \
0    A1  2016  12500       Manual    15735   Petrol  150.0  55.4         1.4   
1    A6  2016  16500    Automatic    36203   Diesel   20.0  64.2         2.0   

   Make  
0  audi  
1  audi

In [66]:
car['tax'].apply(lambda x:x+3)

0        153.0
1         23.0
2         33.0
3        148.0
4        148.0
         ...  
72430      3.0
72431     33.0
72432     23.0
72433    148.0
72434    128.0
Name: tax, Length: 72435, dtype: float64

In [68]:
car['tax']=car['tax'].apply(lambda x:x+3)

In [69]:
car

model  year  price transmission  mileage fuelType    tax   mpg  \
0           A1  2016  12500       Manual    15735   Petrol  153.0  55.4   
1           A6  2016  16500    Automatic    36203   Diesel   23.0  64.2   
2           A1  2016  11000       Manual    29946   Petrol   33.0  55.4   
3           A4  2016  16800    Automatic    25952   Diesel  148.0  67.3   
4           A3  2016  17300       Manual     1998   Petrol  148.0  49.6   
...        ...   ...    ...          ...      ...      ...    ...   ...   
72430      I30  2016   8680       Manual    25906   Diesel    3.0  78.4   
72431      I40  2016   7830       Manual    59508   Diesel   33.0  65.7   
72432      I10  2016   6830       Manual    13810   Petrol   23.0  60.1   
72433   Tucson  2016  13994       Manual    23313   Petrol  148.0  44.8   
72434   Tucson  2016  15999    Automatic    11472   Diesel  128.0  57.6   

       engineSize     Make  
0             1.4     audi  
1             2.0     audi  
2             1.4     audi  
3             2.0     audi  
4             1.0     audi  
...           ...      ...  
72430         1.6  Hyundai  
72431         1.7  Hyundai  
72432         1.0  Hyundai  
72433         1.6  Hyundai  
72434         1.7  Hyundai  

[72435 rows x 10 columns]

By Mufaddal Pathan